name: Deploy to Github Pages Repository

on:
  push:
    branches:
      - master
    paths:
      - "out/**"
      - ".github/workflows/deploy-pages.yml"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              env:
                  ACCESS_TOKEN_GITHUB: '${{ secrets.ACCESS_TOKEN_GITHUB }}'
                  EMAIL: '${{ secrets.EMAIL }}'
            - run: |
                  git config --global user.email "${{secrets.EMAIL}}"
                  git config --global user.name "Michael May"
                  git config --global http.postBuffer 524288000
                  git config --global credential.helper cache
                  git clone https://${{secrets.ACCESS_TOKEN_GITHUB}}@github.com/penguinstein/penguinstein.github.io.git pages
                  cp -rf ./out/* ./pages/
                  cd pages
                  git add .
                  git commit -m "Built latest;"
                  git push origin master
